### ISSUE TITLE
OS error

### ISSUE THREAD

**Issue by toto2pech** [keflavich/pyradex#12]
Hi,
I followed the instructions to install pyradex. In my .bashrc I have the following:
export RADEX_DATAPATH=/Users/toto2pech/CODES/RADEX_PYTHON/pyradex
and here are the python etc... versions:
python -c "import sys, astropy, numpy; print(sys.version); print(numpy.__version__,astropy.__version__)" 
2.7.12 (default, Oct 11 2016, 14:42:58) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
('1.11.2', u'1.2')

gfortran --version
GNU Fortran (MacPorts gcc5 5.4.0_0) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.

OS X El Capitan, version 10.11.6

I do have the following error with the h2co_grids.py script (and for other scripts with the same error) that I don't know how to deal with:

python h2co_grids.py
Traceback (most recent call last):
  File "h2co_grids.py", line 30, in <module>
    R = pyradex.Radex(species='oh2co-h2', abundance=abundance)
  File "/Users/toto2pech/CODES/RADEX_PYTHON/pyradex/pyradex/core.py", line 314, in __init__
    raise ValueError("Must specify two of column, density, and abundance.")
ValueError: Must specify two of column, density, and abundance.
Many thanks for your help!

**Comment by keflavich** [comment]
Your `RADEX_DATAPATH` should not include your global `PATH`.  Instead of:
```
export RADEX_DATAPATH=/Users/toto2pech/CODES/RADEX_PYTHON/pyradex:$PATH
```
you want
```
export RADEX_DATAPATH=/Users/toto2pech/CODES/RADEX_PYTHON/pyradex
```

**Comment by toto2pech** [comment]
Thanks!
Is is me or there is something wrong in the h2co_grids.py (and others, same error) prog?:
python h2co_grids.py
Traceback (most recent call last):
  File "h2co_grids.py", line 30, in <module>
    R = pyradex.Radex(species='oh2co-h2', abundance=abundance)
  File "/Users/toto2pech/CODES/RADEX_PYTHON/pyradex/pyradex/core.py", line 314, in __init__
    raise ValueError("Must specify two of column, density, and abundance.")
ValueError: Must specify two of column, density, and abundance.
Sorry...

**Comment by keflavich** [comment]
Yes, that looks like a real error.  Would you be interested in submitting a pull request to fix it?

**Comment by toto2pech** [comment]
> On 14 Dec 2016, at 16:38, Adam Ginsburg <notifications@github.com> wrote:
> 
> Yes, that looks like a real error. Would you be interested in submitting a pull request to fix it?
> 
I updated my “request” on the website.
Thanks!!
