### ISSUE TITLE
Compilation problems with numpy 1.12

### ISSUE THREAD

**Issue by abeelen** [keflavich/pyradex#14]
[mostly for reference]

The `f2py`  version shipped with `numpy==1.12` will not allow the compilation of `Radex`, leading to error messages like :

```
	Reading file 'radex.inc' (format:fix)
Line #49 in radex.inc:"      parameter(hplanck = 6.6260963d-27)  "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
```

This is due to https://github.com/numpy/numpy/issues/8479 . Note that there is no problem with 1.11 and should be fixed with `numpy==1.12.1`

**Comment by keflavich** [comment]
Thanks.  I'll close this since it contains its own solution, but I appreciate having a problem solved before it gets big!
