### ISSUE TITLE
Missing Output Parameters

### ISSUE THREAD

**Issue by gianninapr** [keflavich/pyradex#25]
If we take a look at the example output of RADEX, the following columns are displayed:

![Screen Shot 2019-07-09 at 1 20 35 PM](https://user-images.githubusercontent.com/39547400/60920218-8b4ffc80-a24c-11e9-9d26-2a6670881ac1.png)

But when I run the same example through pyradex, there are the following output columns:

![Screen Shot 2019-07-09 at 1 20 44 PM](https://user-images.githubusercontent.com/39547400/60920268-a1f65380-a24c-11e9-8c79-2bc343607ec8.png)

I wonder if I'm missing something, or if the values were not included in pyradex on purpose, but I'm trying to get the Flux value (in K * km /s) from Radex (you can see it in the first screenshot) and I don't find a way to get it from pyradex. The flux density property offered by pyradex is not equivalent to this value.

The flux is found under `io.f` in the original RADEX fortran source code as the variable `kkms`. There are other parameters that are calculated within `io.f`. I noticed all the parameters pyradex gives are grabbed from `radex.inc`, yet both flux parameters are sourced in `io.f`. If I had a better understanding of fortran maybe I could help. Is it possible to get values from `io.f`? I see that under `install_radex.py` the `io.f` file isn't read explicitly into python like the others, maybe this could be a way to build bridge to these values? I'm unsure because I'm not familiar with fortran.  I could also email the RADEX authors about including `kkms` flux as a common variable under `radex.inc` if nothing else works or if we can't source these values from `io.f` directly.

**Comment by keflavich** [comment]
If you know the linewidth you're modeling, K kms = 2 sigma `Radex.T_B`
