### ISSUE TITLE
can't "import pyradex"

### ISSUE THREAD

**Issue by irc10216** [keflavich/pyradex#28]
Hi,
 when I try to run pyradex, i get the following error (i have set the env variable RADEX_DATAPATH=/usr/local/pyradex/Radex/data/)

sahai@ppn:/<1>local/pyradex>python
Python 2.7.16 (default, Apr 30 2019, 15:54:59)
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyradex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyradex/__init__.py", line 7, in <module>
    from . import radex
  File "pyradex/radex/__init__.py", line 1, in <module>
    from . import radex

(INFO ABOUT MY COMPUTER)
python -c "import sys, astropy, numpy; print(sys.version); print(numpy.__version__,astropy.__version__)"
2.7.16 (default, Apr 30 2019, 15:54:59) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
('1.15.1', u'2.0.8')

sahai@ppn:/<1>local/pyradex>gfortran --version
GNU Fortran (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by keflavich** [comment]
I suggest switching to python 3, as python 2 will be officially unsupported within a month.

Could you please reproduce the full error?  I don't see any error message in the text you posted; it looks like you only included part of the traceback
